import AdmZip from 'adm-zip';
import { config } from '../config.js';

export interface SuiteData {
  id: string;
  title: string;
  description?: string;
}

export interface SuiteCourse {
  id: string;
  title: string;
  description?: string;
  sortOrder: number;
}

export interface ConsumerCredentials {
  lti_consumer_key: string;
  lti_consumer_secret: string;
}

/**
 * Generates an IMS Common Cartridge (IMSCC) file for a suite of courses
 * Compatible with Canvas, Moodle, Brightspace, and other LMS platforms
 */
export function generateIMSCC(
  suite: SuiteData,
  courses: SuiteCourse[],
  consumer: ConsumerCredentials
): Buffer {
  const zip = new AdmZip();
  const launchUrl = `${config.baseUrl}/lti/launch`;

  // Generate unique identifiers
  const manifestId = `MANIFEST-${suite.id}`;
  const orgId = `ORG-${suite.id}`;

  // Build resources and items arrays
  const resources: string[] = [];
  const items: string[] = [];

  courses.forEach((course, index) => {
    const resourceId = `LTI_${course.id.replace(/-/g, '_')}`;
    const itemId = `ITEM_${course.id.replace(/-/g, '_')}`;
    const ltiFileName = `lti_links/${resourceId}.xml`;

    // Create LTI link file for each course
    const ltiXml = generateLTILinkXml(course, launchUrl, consumer);
    zip.addFile(ltiFileName, Buffer.from(ltiXml, 'utf-8'));

    // Add to resources list
    resources.push(`
    <resource identifier="${resourceId}" type="imsbasiclti_xmlv1p0">
      <file href="${ltiFileName}"/>
    </resource>`);

    // Add to organization items
    items.push(`
      <item identifier="${itemId}" identifierref="${resourceId}">
        <title>${escapeXml(course.title)}</title>
      </item>`);
  });

  // Generate the main manifest
  const manifest = generateManifestXml(
    manifestId,
    orgId,
    suite.title,
    suite.description || '',
    items.join(''),
    resources.join('')
  );

  zip.addFile('imsmanifest.xml', Buffer.from(manifest, 'utf-8'));

  // Add CC schema files indicator (for validation)
  const schemaInfo = `<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
  <!-- IMS Common Cartridge 1.1.0 -->
  <!-- Generated by SCORM-LTI Proxy -->
</schema>`;
  zip.addFile('cc_schema/schema_info.xml', Buffer.from(schemaInfo, 'utf-8'));

  return zip.toBuffer();
}

/**
 * Generates the imsmanifest.xml content
 */
function generateManifestXml(
  manifestId: string,
  orgId: string,
  title: string,
  description: string,
  itemsXml: string,
  resourcesXml: string
): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<manifest identifier="${manifestId}"
    xmlns="http://www.imsglobal.org/xsd/imsccv1p1/imscp_v1p1"
    xmlns:lom="http://ltsc.ieee.org/xsd/imsccv1p1/LOM/resource"
    xmlns:lomimscc="http://ltsc.ieee.org/xsd/imsccv1p1/LOM/manifest"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.imsglobal.org/xsd/imsccv1p1/imscp_v1p1 http://www.imsglobal.org/profile/cc/ccv1p1/ccv1p1_imscp_v1p2_v1p0.xsd
                        http://ltsc.ieee.org/xsd/imsccv1p1/LOM/resource http://www.imsglobal.org/profile/cc/ccv1p1/LOM/ccv1p1_lomresource_v1p0.xsd
                        http://ltsc.ieee.org/xsd/imsccv1p1/LOM/manifest http://www.imsglobal.org/profile/cc/ccv1p1/LOM/ccv1p1_lommanifest_v1p0.xsd">

  <metadata>
    <schema>IMS Common Cartridge</schema>
    <schemaversion>1.1.0</schemaversion>
    <lomimscc:lom>
      <lomimscc:general>
        <lomimscc:title>
          <lomimscc:string language="en-US">${escapeXml(title)}</lomimscc:string>
        </lomimscc:title>
        <lomimscc:description>
          <lomimscc:string language="en-US">${escapeXml(description)}</lomimscc:string>
        </lomimscc:description>
      </lomimscc:general>
    </lomimscc:lom>
  </metadata>

  <organizations>
    <organization identifier="${orgId}" structure="rooted-hierarchy">
      <item identifier="ROOT">
        <title>${escapeXml(title)}</title>
        ${itemsXml}
      </item>
    </organization>
  </organizations>

  <resources>
    ${resourcesXml}
  </resources>

</manifest>`;
}

/**
 * Generates an LTI Basic Launch link XML file
 */
function generateLTILinkXml(
  course: SuiteCourse,
  launchUrl: string,
  consumer: ConsumerCredentials
): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<cartridge_basiclti_link
    xmlns="http://www.imsglobal.org/xsd/imslticc_v1p0"
    xmlns:blti="http://www.imsglobal.org/xsd/imsbasiclti_v1p0"
    xmlns:lticm="http://www.imsglobal.org/xsd/imslticm_v1p0"
    xmlns:lticp="http://www.imsglobal.org/xsd/imslticp_v1p0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.imsglobal.org/xsd/imslticc_v1p0 http://www.imsglobal.org/xsd/lti/ltiv1p0/imslticc_v1p0.xsd
                        http://www.imsglobal.org/xsd/imsbasiclti_v1p0 http://www.imsglobal.org/xsd/lti/ltiv1p0/imsbasiclti_v1p0.xsd
                        http://www.imsglobal.org/xsd/imslticm_v1p0 http://www.imsglobal.org/xsd/lti/ltiv1p0/imslticm_v1p0.xsd
                        http://www.imsglobal.org/xsd/imslticp_v1p0 http://www.imsglobal.org/xsd/lti/ltiv1p0/imslticp_v1p0.xsd">

  <blti:title>${escapeXml(course.title)}</blti:title>
  <blti:description>${escapeXml(course.description || '')}</blti:description>
  <blti:launch_url>${escapeXml(launchUrl)}</blti:launch_url>

  <blti:custom>
    <lticm:property name="course_id">${course.id}</lticm:property>
  </blti:custom>

  <blti:extensions platform="canvas.instructure.com">
    <lticm:property name="tool_id">scorm_lti_proxy_${course.id}</lticm:property>
    <lticm:property name="privacy_level">public</lticm:property>
    <lticm:options name="resource_selection">
      <lticm:property name="enabled">false</lticm:property>
    </lticm:options>
  </blti:extensions>

  <blti:extensions platform="edu.d2l">
    <lticm:property name="ext_d2l_link_id">${course.id}</lticm:property>
  </blti:extensions>

  <blti:extensions platform="moodle.org">
    <lticm:property name="launchcontainer">3</lticm:property>
  </blti:extensions>

  <blti:vendor>
    <lticp:code>scorm-lti-proxy</lticp:code>
    <lticp:name>SCORM-LTI Proxy</lticp:name>
    <lticp:description>Centrally hosted SCORM content with LTI integration</lticp:description>
    <lticp:url>${escapeXml(config.baseUrl)}</lticp:url>
  </blti:vendor>

</cartridge_basiclti_link>`;
}

/**
 * Escape special XML characters
 */
function escapeXml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}
